### ISSUE TITLE
Zetta accepts any URL for the WebSocket stream

### ISSUE THREAD

**Issue by kyork-cl** [zettajs/zetta#263]
Connecting to `ws://zetta-v1-beta.herokuapp.com` times out after 30 seconds with a 503.  Seems like this should be a 404.

Connecting to `ws://zetta-v1-beta.herokuapp.com/events1234` or `ws://zetta-v1-beta.herokuapp.com/events/whatsupdoc` connects and seems to be going to the same handler as `ws://zetta-v1-beta.herokuapp.com/events`

**Comment by AdamMagaluk** [comment]
So it would be pretty easy to send the client a 404 if the url did not match one of our zetta supported ones. We do some checking here: https://github.com/zettajs/zetta/blob/master/lib/http_server.js#L63

However this breaks any custom websocket servers added through an app because zetta does not know about the custom endpoints. @kevinswiber @mdobson Any thoughts on how to handle both cases?

**Comment by AdamMagaluk** [comment]
This is fixed in `v1.0.0-beta.5`
